# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44cb457ef57da731531dcc42dd806722de8f821a0fdbaeee09fb1650031ed558a4ea6700e73330aab1696cfd0b40197774d4656a78d25ca5cc29be7711f07ce0

test:
  secret_key_base: e32eef177a6e52dcdf29dc76fefe7bda5ea495793f6e22ec8084d767fb3ac0b07071700d2ede2799e3344bb4dfe27aa912c0cae9008e23e071cd51fdd36cad36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
